#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Renew the TLS Certificate for all Certificate Authorities and Associated Nodes
  hosts: localhost
  vars_files:
      - org1-vars.yml
  tasks:
      - name: Get the ALL Certificate Authorities
        hyperledger.fabric_ansible_collection.certificate_authority_list_info:
            api_endpoint: "{{ api_endpoint }}"
            api_authtype: "{{ api_authtype }}"
            api_key: "{{ api_key }}"
            api_secret: "{{ api_secret | default(omit) }}"
            api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        register: result

      - name: Store the Certificate Authorities in a file
        copy:
            content: "{{ result.certificate_authorities | to_nice_json }}"
            dest: "All_CAs.json"

      - name: Renew TLS Certificates for Certificate Authorities
        include_tasks: 27-renew-ca-tls-task.yml
        loop: "{{ result.certificate_authorities }}"
        loop_control:
          loop_var: certificate_authority


