#
# SPDX-License-Identifier: Apache-2.0
#
---
state: present
target: openshift
# arch: amd64 | s390x
# project: my-project
namespace: ""

image_pull_secret: cp-pull-secret
image_registry: icr.io
image_repository: cpopen
image_registry_url: "{{ image_registry }}/{{ image_repository }}"
# image_registry_username: cp
# image_registry_email: user@example.org
# image_registry_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

role: "{{ project | default(namespace) | default('') }}"
role_binding: "{{ project | default(namespace) | default('') }}"
security_context_constraints: "{{ project | default(namespace) | default('') }}"
service_account: webhook
wait_timeout: 60

product_version: "1.0.5"
webhook_version: "20230418"
webhook_image: "{{ image_registry_url }}/ibm-hlfsupport-crdwebhook"
webhook_tag: "{{ product_version }}-{{ webhook_version }}-{{ arch }}"
