#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Update anchor peers
  hosts: localhost
  vars_files:
      - common-vars.yml
      - channels.yml
  tasks:

      - name: Create the local msp for all organizations
        hyperledger.fabric_ansible_collection.membership_service_provider_local:
            api_endpoint: "{{ api_endpoint }}"
            api_authtype: "{{ api_authtype }}"
            api_key: "{{ api_key }}"
            api_secret: "{{ api_secret | default(omit) }}"
            api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
            operation: "create"

      - name: Remove the previous channels directory if it exists
        ansible.builtin.file:
            path: channels_anchor
            state: absent

      - name: Remove the previous completed channels
        ansible.builtin.file:
            path: completed_channels.txt
            state: absent

      - name: Update channels
        include_tasks: tasks/05-update-channel.yml
        loop: "{{ channel_names }}"
        loop_control:
            loop_var: channel_name
