#
# SPDX-License-Identifier: Apache-2.0
#
---
state: present
target: openshift
# arch: amd64 | s390x
# project: my-project
namespace: ""

image_pull_secret: cp-pull-secret
image_registry: icr.io
image_repository: cpopen
image_folder: ibm-hlfsupport
image_registry_url: "{{ image_registry }}/{{ image_repository }}/{{ image_folder }}"
# image_registry_username: cp
# image_registry_email: user@example.org
# image_registry_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

cluster_role: "{{ project | default(namespace) | default('') }}"
cluster_role_binding: "{{ project | default(namespace) | default('') }}"
pod_security_policy: "{{ project | default(namespace) | default('') }}"
role_binding: "{{ project | default(namespace) | default('') }}"
security_context_constraints: "{{ project | default(namespace) | default('') }}"
service_account: default
operator: ibm-hlfsupport-operator
console: ibm-hlfsupport-console

# console_domain: example.org
# console_email: user@example.org
# console_default_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
console_storage_class: default
console_storage_size: 10Gi

wait_timeout: 60
product_version: "1.0.5"
operator_version: "20230418"
operator_image: "{{ image_registry }}/{{ image_repository }}/ibm-hlfsupport-operator"
operator_tag: "{{ product_version }}-{{ operator_version }}-{{ arch }}"
# console_tls_secret: ibp-tls-secret
# zones: []
